### PR TITLE
[JENKINS-33685] It adds a configuration option to suppress stack trace always

### PR DESCRIPTION
**Pull request by kuisathaverat**
It adds a configuration option to suppress stack trace always, even if you have administration permission.

### CODE REVIEW

**Comment by kuisathaverat** [comment]
@reviewbybees

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by oleg-nenashev** [comment]
:ant: "Always" is not extensible, the documentation describes a bit different case ("Admins only"). I would recommend creating "suppressForAdmins" and "suppressForUsers" controls instead

**Comment by kuisathaverat** [comment]
@oleg-nenashev 
I changed it to had three options to choice:
Users - It suppress stack trace for users, administrators could see the stack trace.
Users and administrators -It always suppress stack trace even if the user is administrator.
Nobody - It always shows the stack trace.

**Comment by jglick** [comment]
What exactly is the purpose of this? If you are an administrator, there is no security risk in seeing the stack trace. That is why the plugin displays it.

[JENKINS-33685](https://issues.jenkins-ci.org/browse/JENKINS-33685) does not offer any further justification, only repeats the proposed change.

Everyone pays a toll when you add a new global UI configuration option, so the onus is on you to demonstrate that there is no reasonable alternative.

**Comment by kuisathaverat** [comment]
@jglick 
the plugin still works by default as works before, so no affects to previous configurations. The justification is to give the option to suppress all stack trace even if the user is administrator, or allow temporarily  to see stack traces. It is true that displays to administrator the stack trace is not a security risk so in this case is a simple esthetic change.

**Pull request closed without merging**
