### PR TITLE
[JENKINS-60410] This plugin is unnecessary as of 2.224

### PR DESCRIPTION
**Pull request by jglick**
This just clashes with the built-in feature in https://github.com/jenkinsci/jenkins/pull/4389 IIUC, so we should make it a no-op.

Noticed because it actively breaks https://github.com/jenkinsci/jenkins/pull/4848: bypasses `ExceptionTranslationFilter`.

### CODE REVIEW

**Review by daniel-beck — APPROVED** [review]
Untested. Core dependency looks correct.

**Review by jeffret-b — APPROVED** [review]
Looks good. I'm glad to get this cleaned up after introducing the capabilities into core. I forgot about following up on that once we got it integrated.

**Comment by daniel-beck** [comment]
Alternatively (or in addition), we could mark it as deprecated (https://github.com/jenkins-infra/update-center2#deprecations) and then Jenkins 2.248+ will show this plugin in an admin monitor.

**Comment by jglick** [comment]
I plan to also mark it `deprecated` but am waiting on an `INFRA` ticket before I am permitted to do so.

**Pull request merged**
